server:
  servlet:
    context-path: "{{ .Values.contex_path }}"
  port: "{{ .Values.port }}"
  max-http-header-size: 10MB
spring:
  datasource:
    url: {{ .Values.database.url }}
    username: {{ .Values.database.username }}
    password: {{ .Values.database.password }}
  servlet:
    multipart:
      max-file-size: 5MB
      file-size-threshold: 1KB
      max-request-size: 6MB

developer:
  key:
    value: "This is from configuration"

management:
  endpoints:
    web:
      exposure:
        include: '*'